### ISSUE TITLE
Updated packages

### ISSUE THREAD

**Issue by JanMarcoRuizdeVargas** [huawei-noah/trustworthyAI#108]
When trying the usage example on python 3.10 i get an nx error, it seems a newer version of nx changed nx.to_numpy_matrix to nx.to_numpy_array. 
Can you please clarify on the versions needed for running gcastle?
Additionally, what would be needed to update it to python 3.10+?

**Comment by shaido987** [comment]
Hello,

Yes, the problem lies in newer versions of networkx removed the `to_numpy_matrix` method. A fix was very recently merged into the code, see https://github.com/huawei-noah/trustworthyAI/pull/106, but this has not been added to PyPI yet (so using pip will still install the version before this fix). 

For now, you can use an older version of networkx:

```
pip install networkx==2.7
```

or manually build gCastle from GitHub by cloning the repo and running `pip install .` in the gCastle folder.


For Python 3.10, you can try it out first and see how it works out.

**Comment by JanMarcoRuizdeVargas** [comment]
Cool thanks for the answer!
