### ISSUE TITLE
Compatibility and installation issues

### ISSUE THREAD

**Issue by tomsons22** [huawei-noah/trustworthyAI#30]
Hi,

First of all, thanks for the great package! Having all causal discovery algorithms with a unified interface is extremely useful.

I'm trying to use gcastle as part of a larger system that uses the latest version of tensorflow. However, gcastle requires tensorflow 1.15, and is not compatible with later versions. I think this is mainly due to its import statements, which refer to some directories that are not there any more in the newer tensorflow version. For instance, it has "from tensorflow.contrib import distributions". The directory tensorflow.contrib is not there anymore, and now distributions are in the probability directory. Are you aware of any other potential sources of incompatibility? Or is it just the imports? 

Also, are you planning on updating the code to make it compatible with newer versions of tensorflow?

Thanks!

**Comment by shaido987** [comment]
Hello, 

Thanks for your interest.  
The plan forward is to entirely remove the usage and dependency on tensorflow. This is something we hope to achieve with the next release of the package (~October). 

There could be other potential issues due to updating to use tensorflow 2+ (although it should work by adding `tf.disable_v2_behavior()`, however, it would still require some testing). As the package will be removed soon we don't think it's necessary to update the version at this time.

**Comment by tomsons22** [comment]
Thanks for the prompt reply. Makes sense. Looking forward to the new release.
