### ISSUE TITLE
Can't successfully install CAM package

### ISSUE THREAD

**Issue by smile0925** [huawei-noah/trustworthyAI#34]
I download the CAM_1.0.tar.gz and run the setup_CAM.py, but when check if CAM and mboost have been installed, get 'need to install CAM and mboost'. I can't install CAM successfully.
![image](https://user-images.githubusercontent.com/46243662/139454888-f08964e8-3ebf-48bf-8dcf-f8bc8f01b89b.png)

**Comment by shertheus** [comment]
Did you solve it? I also encountered the same problem.

**Comment by shertheus** [comment]
> I download the CAM_1.0.tar.gz and run the setup_CAM.py, but when check if CAM and mboost have been installed, get 'need to install CAM and mboost'. I can't install CAM successfully. ![image](https://user-images.githubusercontent.com/46243662/139454888-f08964e8-3ebf-48bf-8dcf-f8bc8f01b89b.png)
Did you solve it? I also encountered the same problem.

**Comment by shaido987** [comment]
It's possible that the problem is due to some missing dependencies that can occur when running on a linux based system. You can try and see if the fix mentioned [here](https://github.com/r-lib/devtools/issues/2131#issue-504093105) solves the issue, i.e., running:

```bash
sudo apt install build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev
```

**Comment by shaido987** [comment]
@cczhangy You can try to install CAM using the RStudio IDE instead of using rpy2. 

1. First, make sure R is installed (https://cran.r-project.org/).
2. Install RStudio from https://www.rstudio.com/products/rstudio/download/
3. Install all dependences, i.e.: Matrix, mgcv, codetools, rpart, glmnet, mboost. See here for a quick how-to: http://derekogle.com/IFAR/supplements/installations/InstallPackagesRStudio.html
4. Download CAM_1.0.tar.gz from https://cran.r-project.org/package=CAM
5. Install using the same method as in 3, but change 'install from' to 'Package Archive File' and select the downloaded CAM_1.0.tar.gz file.

You can now use python to check so rpy2 can access the installed packages:

```python
import rpy2.robjects.packages as rpackages

utils = rpackages.importr('utils')

if rpackages.isinstalled('CAM') and rpackages.isinstalled('mboost'):
    print('R packages CAM and mboost have been installed.')
else:
    print('Packages not installed correctly.')
```

**Comment by cczhangy** [comment]
@shaido987 I have executed as you said and got the following two errors when running
python version3.6.13
    from typing import Protocol
ImportError:cantnot import name 'Protocol'

AttributeError:module 'typing' has no attribute '_SpecialForm'

**Comment by shaido987** [comment]
@cczhangy It looks like you have some python versioning issue unrelated to the CAM package installation. I don't know what is wrong but the answers here: https://stackoverflow.com/questions/54274630/can-not-import-protocol-from-typing, suggest installing/upgrading the typing_extensions package or upgrading the python version.

**Comment by cczhangy** [comment]
Ok,thank you very much!
