### ISSUE TITLE
Dataset Details

### ISSUE THREAD

**Issue by gwinch97** [huawei-noah/trustworthyAI#65]
Hi,

Thank you for releasing the three datasets from your Causal Discovery competition in 2021. I was just wondering if there were more details on these datasets? Or more specifically, are these sub-sampled data from the full datasets described in the papers [arXiv:2105.10884](https://arxiv.org/abs/2105.10884) and [arXiv:2105.03092](https://arxiv.org/abs/2105.03092)?

Many thanks

**Comment by shaido987** [comment]
Hello,

The three datasets released for the competition were collected separately from the datasets in the papers (and are thus not sub-sampled from these). However, there are similarities:

The dataset used by THP (https://arxiv.org/abs/2105.10884) is a microwave dataset. Any data descriptions there are relevant for the microwave competition data, see e.g. Appendix I in the paper. There are some differences due to preprocessing decisions so it's not fully identical.

For HPCI (https://arxiv.org/abs/2105.03092), it uses a wireless dataset so any information there is largely applicable to the released wireless competition dataset. I've been told that the entire or at least a large part of the dataset used by HPCI can be released soon, so hopefully, there should be another larger dataset available in the near future.
