### ISSUE TITLE
请问True Causal Graph的文件格式是什么样的？ 可以提供个例子吗？

### ISSUE THREAD

**Issue by Congwen-Wang** [huawei-noah/trustworthyAI#69]
你好，感谢你们做出这个强大和好用的因果发现library。

通过CastleBoard，我已经成功生成了因果图。但在评价时，不知道该提供什么样的True Causal Graph文件，可以提供个例子吗？谢谢

（如果我遗漏了什么，十分抱歉。）

**Comment by shaido987** [comment]
Hello,

Although I know a bit of Chinese, I'm in no way fluent so I will answer in English.

If you used the GUI to create a dataset using the "Dataset Generation" (数据生成) task, then the true causal graph is already known. When looking at the created graph and clicking Evaluate/评价, you can select "Use an built-in True Causal Graph"/内置真实因果图 and select the dataset you created before. This will compute all wanted evaluation metrics for you.

If you are using another dataset that is not created by using the GUI, then you should either know the true causal graph (in which case you can provide it to compute the evaluation metrics), or its unknown and its impossible to evaluated the results (since the metrics compare the prediction with the ground-truth).

**Comment by Congwen-Wang** [comment]
Hi shaido987,

Thank you for your reply.  I am using the 'Causal discovery' task. I know the true causal graph.

But I don't know what file type should the true causal graph be or what style the content of the graph is.

Could you please provide an example of a true causal graph?

Thank you so much!

**Comment by shaido987** [comment]
I see, the input for the user-defined true causal graph should be a numpy matrix, for example:

```python
array([[0., 0., 0., 0., 0.],
          [0., 0., 1., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 1., 1., 0., 0.],
          [1., 1., 1., 1., 0.]])
```

The above matrix has 7 edges (0 indexed): 1 -> 2, 1 -> 3, 2 -> 3, 0 -> 4, 1 -> 4, 2 -> 4, and 3 -> 4.

You can save the matrix using `np.savetxt(path_to_save, delimitar=',')` and hen use the path to the saved file in the GUI.

**Comment by peterzhb** [comment]
> I see, the input for the user-defined true causal graph should be a numpy matrix, for example:
> 
> ```python
> array([[0., 0., 0., 0., 0.],
>        [0., 0., 1., 0., 0.],
>        [0., 0., 0., 0., 0.],
>        [0., 1., 1., 0., 0.],
>        [1., 1., 1., 1., 0.]])
> ```
> 
> The above matrix has 7 edges (0 indexed): 1 -> 2, 1 -> 3, 2 -> 3, 0 -> 4, 1 -> 4, 2 -> 4, and 3 -> 4.
> 
> You can save the matrix using `np.savetxt(path_to_save, delimiter=',')` and then use the path to the saved file in the GUI.

补充：横坐标是from，纵坐标是to。

**Comment by Congwen-Wang** [comment]
Hi shaido987 and peterzhb, 

Thank you so much for your replay. I'm sorry that some errors have occurred and that it has not yet worked. Please give me some time. I will try again and reply. Once again, thank you very much.
