### ISSUE TITLE
task of data generation

### ISSUE THREAD

**Issue by sususnow** [huawei-noah/trustworthyAI#76]
Hi. When I use the GUI web for the task of data generation. I found that the edges in the graph are not equal to those in the configuration parameters. When I change the seed while keeping the n_nodes and n_edges identical, the edges in the graph may also be changed. So What's the effect of seed? Thanks.

**Comment by shaido987** [comment]
Hello,

The data generation in the web GUI uses the DAG.erdos_renyi method to simulate a random weighted DAG:
https://github.com/huawei-noah/trustworthyAI/blob/2e08a7aab82e7ea6ba340ecbfccb427b67e3be3f/gcastle/castle/datasets/simulator.py#L161-L174

The [Erdős–Rényi](https://en.wikipedia.org/wiki/Erd%C5%91s%E2%80%93R%C3%A9nyi_model) model is built upon the idea that each edge in the graph has a fixed probability of being present or absent. As you can see in the code above, we approximate a probability given `n_nodes` and `n_edges`. Since the graph generation is random, the final number of edges in the graph may vary. The number of edges should be consistent for the same `seed`.
